---
- name: app | Change symlink from current release to a previous one
  file:
    state: link
    path: "{{ nodejs_app_path }}/{{ app_current_dir }}"
    src: "{{ nodejs_app_path }}/{{ app_version_dir }}/{{ app_current_dir }}"
