---
- cron:
    name: "LogParser"
    minute: "0"
    hour: "1,2"
    job: "{{ nodejs_app_path }}/logparser.sh"

- cron:
    name: "SentEmail.js"
    minute: "0"
    hour: "1,3"
    job: "node {{ nodejs_app_path }}/email.js"
